MODEL:
    architecture: "ETESVS"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth"
        clip_seg_num: 30
        shift_div: 30
    neck:
        name: "ETESVSNeck"
        num_classes: 48
        num_layers: 1
        num_stages: 1
        in_channel: 1280
        clip_seg_num: 30
        drop_ratio: 0.5
        bidirectional: False
    head:
        name: "ETESVSHead"
        num_classes: 48
        num_layers: 4
        sliding_window: 120
        seg_in_channels: 1280
        sample_rate: 4
        num_f_maps: 64
    loss:
        name: "ETESVSLoss"
        num_classes: 48
        sample_rate: 4
        seg_weight: 1.0
        cls_weight: 1.0
        ignore_index: -100

COLLATE:
    to_tensor_idx: 3

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 4
    num_workers: 2
    train:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth"
        actions_map_file_path: "./data/breakfast/mapping.txt"
        dataset_type: "breakfast"
        train_mode: True
        sliding_window: 120
        clip_seg_num: 30
        sample_rate: 4
    test:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth"
        actions_map_file_path: "./data/breakfast/mapping.txt"
        dataset_type: "breakfast"
        train_mode: False
        sliding_window: 120
        clip_seg_num: 30
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 30
            sliding_window: 120
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: 256
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.425, 0.390, 0.337]
                std: [0.262, 0.260, 0.246]

    test:
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 30
            sliding_window: 120
            sample_mode: "uniform"
        transform:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.425, 0.390, 0.337]
                std: [0.262, 0.260, 0.246]

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.001 # 4 videos * 4 gpus
    step_size: [50]
    gamma: 0.5

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/breakfast/mapping.txt"


model_name: "ETESVS_MobileNetV2_breakfast_split1"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
