MODEL:
    architecture: "Recognition3D"
    backbone:
        name: "PredRNNV2"
        num_layers: 4
        num_hidden: [128, 128, 128, 128]
        img_width: 64
        img_channel: 3
        filter_size: 5
        stride: 1
        layer_norm: False
    neck:
    head:
        name: "I3DHead"
        num_classes: 11
        clip_seg_num: 32
        sample_rate: 4
        drop_ratio: 0.5
        in_channels: 128
    loss:
        name: "RecognitionSegmentationLoss"
        label_mode: "hard"
        num_classes: 11
        sample_rate: 4
        loss_weight: 1.0
        ignore_index: -100

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks" , "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            is_train: True
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: [64, 64]
            - RandomCrop:
                size: 64
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.551, 0.424, 0.179]
                std: [0.133, 0.141, 0.124]

    test:
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            is_train: False
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            - Resize:
                size: [64, 64]
            - CenterCrop:
                size: 64
            - ToTensor:
            - Normalize:
                mean: [0.551, 0.424, 0.179]
                std: [0.133, 0.141, 0.124]

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.00005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"
    file_output: True


model_name: "PredRNNV2_gtea_split1"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
