MODEL:
    architecture: "StreamSegmentation"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/tsm_mobilenetv2_dense_320p_1x1x8_100e_kinetics400_rgb_20210202-61135809.pth"
        clip_seg_num: 32
        shift_div: 8
        out_indices: (7, )
    neck:
        name: "AvgPoolNeck"
        num_classes: 48
        in_channels: 1280
        clip_seg_num: 32
        drop_ratio: 0.5
        need_pool: False
    head:
        name: "TCN3DHead"
        num_classes: 48
        num_layers: 4
        sample_rate: 4
        sliding_window: 128
        seg_in_channels: 1280
        num_f_maps: 64
    loss:
        name: "StreamSegmentationLoss"
        num_classes: 48
        sample_rate: 4
        backone_loss_weight: 1.0
        head_loss_weight: 1.0
        ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks"]

DATASET: #DATASET field
    temporal_clip_batch_size: 2
    video_batch_size: 6
    num_workers: 3
    train:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth"
        actions_map_file_path: "./data/breakfast/mapping.txt"
        dataset_type: "breakfast"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits/test_tiny.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth"
        actions_map_file_path: "./data/breakfast/mapping.txt"
        dataset_type: "breakfast"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: 256
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.425, 0.390, 0.337]
                std: [0.262, 0.260, 0.246]

    test:
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.425, 0.390, 0.337]
                std: [0.262, 0.260, 0.246]

OPTIMIZER:
    name: "TSMSGDOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    momentum: 0.9

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [10, 30]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/breakfast/mapping.txt"
    file_output: True
    score_output: True



model_name: "ETESVS_3D_breakfast_split1"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
