MODEL:
    architecture: "OpticalFlowEstimation"
    model:
        name: "LiteFlowNetV3"
        pretrained: "./data/network-sintel.pytorch"
        freeze: True

DATASET:
    video_path: "./data/gtea/Videos"
    file_list: "./data/gtea/video_list.txt"
    dataset_type: "gtea"
    num_segments: 32
    fps: 15

TRANSFORM: #Mandotary, image transform operator.
    - ToTensor:
    # - Normalize:
    #     mean: [0.551, 0.424, 0.179]
    #     std: [0.133, 0.141, 0.124]