MODEL:
    architecture: "FeatureSegmentation"
    backbone:
    neck:
    head:
        name: "MultiStageModel"
        num_stages: 4
        num_layers: 10
        num_f_maps: 64
        dim: 2048
        num_classes: 178
        sample_rate: 1
    loss:
        name: "SegmentationLoss"
        num_classes: 178
        sample_rate: 1
        smooth_weight: 0.15
        ignore_index: -100

POSTPRECESSING:
    name: "ScorePostProcessing"
    num_classes: 178
    ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_keys: ["feature", "labels", "masks", "precise_sliding_num"]
    compress_keys: ["sliding_num", "current_sliding_cnt"]
    ignore_index: -100

DATASET: #DATASET field
    temporal_clip_batch_size: 8
    video_batch_size: 1
    num_workers: 4
    train:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits_fine/train.split1.bundle" #Mandatory, train data index file path
        feature_path: "./data/breakfast/features"
        gt_path: "./data/breakfast/groundTruth_fine"
        actions_map_file_path: "./data/breakfast/mapping_fine.txt"
        dataset_type: "breakfast"
        sample_rate: 1
    test:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits_fine/test.split1.bundle" #Mandatory, train data index file path
        feature_path: "./data/breakfast/features"
        gt_path: "./data/breakfast/groundTruth_fine"
        actions_map_file_path: "./data/breakfast/mapping_fine.txt"
        dataset_type: "breakfast"
        sample_rate: 1

PIPELINE: #PIPELINE field
    train:
        name: "BasePipline"
        decode:
            name: "FeatureDecoder"
            backend: "numpy"
        sample:
            name: "FeatureSampler"
            is_train: True
            sample_rate: 1
            sample_mode: "uniform"
        transform:
            name: "FeatureStreamTransform"
            transform_list:
              - ToTensor:

    test:
        name: "BasePipline"
        decode:
            name: "FeatureDecoder"
            backend: "numpy"
        sample:
            name: "FeatureSampler"
            is_train: False
            sample_rate: 1
            sample_mode: "uniform"
        transform:
            name: "FeatureStreamTransform"
            transform_list:
              - ToTensor:

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    name: "TASegmentationMetric"
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/breakfast/mapping_fine.txt"
    file_output: True
    score_output: True


model_name: "MSTCN_breakfast_split1"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 35 #Mandatory, total epoch
save_interval: 35
