MODEL:
    architecture: "StreamSegmentation2DWithNeck"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth"
        clip_seg_num: 32
        shift_div: 8
        out_indices: (6, 7, )
    neck:
        name: "ETESVSNeck"
        num_classes: 20
        num_layers: 1
        cls_in_channel: 1280
        cls_hidden_channel: 1280
        seg_in_channel: 320
        seg_hidden_channel: 320
        clip_seg_num: 32
        drop_ratio: 0.5
        bidirectional: False
    head:
        name: "ETESVSHead"
        num_classes: 20
        num_layers: 4
        sample_rate: 4
        sliding_window: 128
        seg_in_channels: 320
        num_f_maps: 64
    loss:
        name: "ETESVSLoss"
        num_classes: 20
        sample_rate: 4
        backone_loss_weight: 1.0
        neck_loss_weight: 1.0
        head_loss_weight: 1.0
        ignore_index: -100

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 6
    num_workers: 3
    train:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/egtea/splits/train_split1.txt" #Mandatory, train data index file path
        videos_path: "./data/egtea/Videos"
        gt_path: "./data/egtea/groundTruth"
        actions_map_file_path: "./data/egtea/mapping.txt"
        dataset_type: "egtea"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/egtea/splits/test_split1.txt" #Mandatory, train data index file path
        videos_path: "./data/egtea/Videos"
        gt_path: "./data/egtea/groundTruth"
        actions_map_file_path: "./data/egtea/mapping.txt"
        dataset_type: "egtea"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train:
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: [256, 320]
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.479, 0.307, 0.176]
                std: [0.264, 0.204, 0.163]

    test:
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            - Resize:
                size: [256, 320]
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.479, 0.307, 0.176]
                std: [0.264, 0.204, 0.163]

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.001
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/egtea/mapping.txt"
    file_output: True
    score_output: True


model_name: "ETESVS_MobileNetV2_egtea_split1"
log_interval: 5 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
