MODEL:
    architecture: "Recognition3D"
    backbone:
        name: "ResNet3d"
        depth: 50
        pretrained: "./data/i3d_r50_video_32x2x1_100e_kinetics400_rgb_20200826-e31c6f52.pth"
        in_channels: 3
        with_pool2: False
        pretrained2d: False
        inflate: [[1, 1, 1], [1, 0, 1, 0], [1, 0, 1, 0, 1, 0], [0, 1, 0]]
        zero_init_residual: False
    neck:
    head:
        name: "FeatureExtractHead"
        in_channels: 2048
        clip_seg_num: 32
        sample_rate: 2
        pool_space: True
        in_format: "N,C,T,H,W"
        out_format: "NCT"
    loss:

# PRETRAINED: ""

POSTPRECESSING:
    name: "FeaturePostProcessing"
    feature_dim: 2048
    clip_seg_num: 32
    sliding_window: 64
    sample_rate: 2
    ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 4
    num_workers: 2
    config:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/thumos14/test_list.txt" #Mandatory, train data index file path
        videos_path: "./data/thumos14/Videos"
        gt_path: "./data/thumos14/groundTruth"
        actions_map_file_path: "./data/thumos14/mapping.txt"
        dataset_type: "thumos14"
        train_mode: False
        sliding_window: 64
        clip_seg_num: 32
        sample_rate: 2

PIPELINE: #PIPELINE field
    name: "RawFramePipeline"
    decode:
        backend: "decord"
    sample:
        is_train: False
        sample_rate: 2
        clip_seg_num: 32
        sliding_window: 64
        sample_mode: "uniform"
    transform:
        - Resize:
            size: [256, 320]
        - CenterCrop:
            size: 224
        - ToTensor:
        - Normalize:
            mean: [0.385, 0.383, 0.353]
            std: [0.258, 0.254, 0.248]