MODEL:
    architecture: "StreamSegmentation3D"
    backbone:
        name: "ResNet3d"
        depth: 50
        pretrained: "./data/i3d_r50_video_32x2x1_100e_kinetics400_rgb_20200826-e31c6f52.pth"
        in_channels: 3
        with_pool2: False
        pretrained2d: False
        inflate: [[1, 1, 1], [1, 0, 1, 0], [1, 0, 1, 0, 1, 0], [0, 1, 0]]
        zero_init_residual: False
    neck:
        name: "AvgPoolNeck"
        num_classes: 48
        in_channels: 2048
        clip_seg_num: 32
        drop_ratio: 0.5
        need_pool: True
        need_pre_cls: False
    head:
        name: "MultiStageModel"
        num_stages: 4
        num_layers: 10
        num_f_maps: 64
        dim: 2048
        num_classes: 48
        sample_rate: 4
    loss:
        name: "SegmentationLoss"
        num_classes: 48
        sample_rate: 4
        smooth_weight: 0.15
        ignore_index: -100

POSTPRECESSING:
    name: "StreamScorePostProcessing"
    num_classes: 48
    clip_seg_num: 32
    sliding_window: 128
    sample_rate: 4
    ignore_index: -100

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks", "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        name: "RawFrameStreamSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits/train.split3.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth"
        actions_map_file_path: "./data/breakfast/mapping.txt"
        dataset_type: "breakfast"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RawFrameStreamSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits/test.split3.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth"
        actions_map_file_path: "./data/breakfast/mapping.txt"
        dataset_type: "breakfast"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        name: "BasePipline"
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "VideoStreamSampler"
            is_train: True
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            name: "VideoStreamTransform"
            transform_list:
                - Resize:
                    size: [256, 320]
                - RandomCrop:
                    size: 224
                - RandomHorizontalFlip:
                - ToTensor:
                - Normalize:
                    mean: [0.425, 0.390, 0.337]
                    std: [0.262, 0.260, 0.246]

    test:
        name: "BasePipline"
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "VideoStreamSampler"
            is_train: False
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            name: "VideoStreamTransform"
            transform_list:
                - Resize:
                    size: [256, 320]
                - CenterCrop:
                    size: 224
                - ToTensor:
                - Normalize:
                    mean: [0.425, 0.390, 0.337]
                    std: [0.262, 0.260, 0.246]

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    name: "TASegmentationMetric"
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/breakfast/mapping.txt"
    file_output: True


model_name: "I3D_MSTCN_breakfast_split3"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 35 #Mandatory, total epoch
save_interval: 35
