MODEL:
    architecture: "StreamSegmentation2DMultiLabel"
    backbone:
        name: "ResNetTSM"
        pretrained: "data/clsLess_tsm_r50_256p_1x1x8_kinetics400_rgb_.pth"
        clip_seg_num: 16
        shift_div: 8
        out_indices: (3, )
    neck:
        name: "AvgPoolNeck"
        num_classes: 39
        in_channels: 2048
        clip_seg_num: 16
        drop_ratio: 0.5
        need_pool: True
    head:
        action_head:
            name: "MemoryTCNHead"
            num_stages: 1
            num_layers: 4
            num_f_maps: 64
            dim: 2048
            num_classes: 11
            sample_rate: 2
        branch_head:
            name: "MemoryTCNHead"
            num_stages: 1
            num_layers: 4
            num_f_maps: 64
            dim: 2048
            num_classes: 28
            sample_rate: 2
        sample_rate: 2
    loss:
        name: "SegmentationLossMultiLabel"
        num_classes_action: 11
        num_classes_branches: 28
        sample_rate: 2
        smooth_weight: 0.15
        ignore_index: -100

POSTPRECESSING:
    name: "StreamScorePostProcessingMultiLabel"
    num_action_classes: 11
    num_branch_classes: 28
    clip_seg_num: 16
    sliding_window: 32
    sample_rate: 2
    ignore_index: -100
  
COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks", "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 2
    video_batch_size: 8
    num_workers: 0
    train:
        name: "RawFrameStreamSegmentationDatasetMultiLabel"
        data_prefix: "./" 
        file_path: "./data/production/splits/train.bundle"
        videos_path: "./data/production/Videos"
        gt_path: "./data/production/groundTruth_split"
        actions_map_file_path: "./data/production/mapping_tasks.txt"
        branches_map_file_path: "./data/production/mapping_branches.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 32
        clip_seg_num: 16
        sample_rate: 2
    test:
        name: "RawFrameStreamSegmentationDatasetMultiLabel"
        data_prefix: "./" 
        file_path: "./data/production/splits/test.bundle" 
        videos_path: "./data/production/Videos"
        gt_path: "./data/production/groundTruth_split"
        actions_map_file_path: "./data/production/mapping_tasks.txt"
        branches_map_file_path: "./data/production/mapping_branches.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 32
        clip_seg_num: 16
        sample_rate: 2

PIPELINE: 
    train: 
        name: "BasePipline"
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "VideoStreamSamplerMultiLabel"
            is_train: True
            sample_rate: 2
            clip_seg_num: 16
            sliding_window: 32
            sample_mode: "uniform"
        transform: 
            name: "VideoStreamTransform"
            transform_list:
                - Resize:
                    size: [224, 224] 
                - RandomCrop:
                    size: 224
                - RandomHorizontalFlip:
                - ToTensor:
                - Normalize:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225] 

    test:
        name: "BasePipline"
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "VideoStreamSamplerMultiLabel"
            is_train: False
            sample_rate: 2
            clip_seg_num: 16
            sliding_window: 32
            sample_mode: "uniform"
        transform:
            name: "VideoStreamTransform"
            transform_list:
                - Resize:
                    size: [224, 224]
                - CenterCrop:
                    size: 224
                - ToTensor:
                - Normalize:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225] 

OPTIMIZER:
    name: "TSMAdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    name: "TASegmentationMetric"
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/production/mapping_split.txt"
    file_output: True
    score_output: True


model_name: "production"
log_interval: 1 #Optional, the interal of logger, default:10
epochs: 200 #Mandatory, total epoch
save_interval: 50
