MODEL:
    architecture: "ETESVS"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth"
        clip_seg_num: 30
        shift_div: 30
    neck:
        name: "ETESVSNeck"
        num_classes: 21
        num_layers: 8
        out_channel: 64
        in_channel: 1280
        clip_seg_num: 30
        drop_ratio: 0.5
        sample_rate: 8
    head:
        name: "ETESVSHead"
        num_classes: 21
        num_layers: 8
        sliding_window: 240
        seg_in_channels: 1280
        sample_rate: 8
        num_f_maps: 64
    loss:
        name: "ETESVSLoss"
        num_classes: 21
        sample_rate: 8
        seg_weight: 1.0
        cls_weight: 1.0
        ignore_index: -100

COLLATE:
    to_tensor_idx: 3

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/thumos14/val_list.txt" #Mandatory, train data index file path
        videos_path: "./data/thumos14/Videos"
        gt_path: "./data/thumos14/groundTruth"
        actions_map_file_path: "./data/thumos14/mapping.txt"
        dataset_type: "thumos14"
        train_mode: True
        sliding_window: 240
        clip_seg_num: 30
        sample_rate: 8
    test:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/thumos14/test_list.txt" #Mandatory, train data index file path
        videos_path: "./data/thumos14/Videos"
        gt_path: "./data/thumos14/groundTruth"
        actions_map_file_path: "./data/thumos14/mapping.txt"
        dataset_type: "thumos14"
        train_mode: False
        sliding_window: 240
        clip_seg_num: 30
        sample_rate: 8

PIPELINE: #PIPELINE field
    train: 
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 8
            clip_seg_num: 30
            sliding_window: 240
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: 256
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.385, 0.383, 0.353]
                std: [0.258, 0.254, 0.248]

    test:
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 8
            clip_seg_num: 30
            sliding_window: 240
            sample_mode: "uniform"
        transform:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.385, 0.383, 0.353]
                std: [0.258, 0.254, 0.248]

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.0005 # 2 gpus * 2 batch size = 4
    step_size: [50]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/thumos14/mapping.txt"
    file_output: True


model_name: "ETESVS_thumos14"
log_interval: 5 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
