MODEL:
    architecture: "FeatureSegmentation"
    backbone:
    neck:
    head:
        name: "MultiStageModel"
        num_stages: 4
        num_layers: 4
        num_f_maps: 64
        dim: 2048
        num_classes: 19
    loss:
        name: "MSTCNLoss"
        num_classes: 19
        sample_rate: 1
        smooth_weight: 0.15
        ignore_index: -100

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["faeture", "labels", "masks"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 4
    num_workers: 4
    train:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/50salads/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/50salads/features"
        gt_path: "./data/50salads/groundTruth"
        actions_map_file_path: "./data/50salads/mapping.txt"
        dataset_type: "50salads"
        train_mode: True
        sliding_window: 640
        clip_seg_num: 640
        sample_rate: 1
    test:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/50salads/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/50salads/features"
        gt_path: "./data/50salads/groundTruth"
        actions_map_file_path: "./data/50salads/mapping.txt"
        dataset_type: "50salads"
        train_mode: False
        sliding_window: 640
        clip_seg_num: 640
        sample_rate: 1

PIPELINE: #PIPELINE field
    train: 
        name: "FeaturePipline"
        decode:
            backend: "numpy"
        sample:
            seg_len: 1
            sample_rate: 1
            clip_seg_num: 640
            sliding_window: 640
            sample_mode: "uniform"
        transform:
            - ToTensor:

    test:
        name: "FeaturePipline"
        decode:
            backend: "numpy"
        sample:
            seg_len: 1
            sample_rate: 1
            clip_seg_num: 640
            sliding_window: 640
            sample_mode: "uniform"
        transform:
            - ToTensor:

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [20, 40]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/50salads/mapping.txt"
    file_output: True
    score_output: True


model_name: "Sliding_MSTCN_50salads_split1"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
