MODEL:
    backbone:
        pretrained: True
        depth: 50
    neck:
        buffer_channels: 512
        hidden_channels: 64
        num_layers: 5
        clip_seg_num: 15
        clip_buffer_num: 0
        sliding_window: 30
    head:
        num_classes: 11
        num_stages: 1
        num_layers: 4
        num_f_maps: 64
        cls_in_channels: 2048
        seg_in_channels: 2048
        sample_rate: 4
        drop_ratio: 0.5
    loss:
        num_classes: 11
        sample_rate: 4
        seg_weight: 1.0
        cls_weight: 1.0
        ignore_index: -100

COLLATE:
    to_tensor_idx: 3

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 8
    num_workers: 8
    train:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/train.split4.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 30
        clip_seg_num: 15
        sample_rate: 4
    test:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split4.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 30
        clip_seg_num: 15
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 15
            sliding_window: 30
        transform: #Mandotary, image transform operator.
            - Resize:
                size: 256
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.551, 0.424, 0.179]
                std: [0.133, 0.141, 0.124]

    test:
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 15
            sliding_window: 30
        transform:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.551, 0.424, 0.179]
                std: [0.133, 0.141, 0.124]

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.0005
    step_size: 50
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"



model_name: "ETETS_gtea_split4"
log_interval: 1 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
