MODEL:
    architecture: "MulModStreamSegmentation"
    rgb_backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/tsm_mobilenetv2_dense_320p_1x1x8_100e_kinetics400_rgb_20210202-61135809.pth"
        in_channels: 3
        clip_seg_num: 32
        shift_div: 8
        out_indices: (7, )
    flow_backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/tsm_mobilenetv2_dense_320p_1x1x8_100e_kinetics400_rgb_20210202-61135809.pth"
        in_channels: 3
        clip_seg_num: 32
        shift_div: 8
        out_indices: (7, )
    audio_backbone:
    neck:
        name: "AvgPoolNeck"
        num_classes: 11
        num_layers: 1
        in_channels: 1280
        clip_seg_num: 32
        drop_ratio: 0.5
        need_pool: False
    head:
        name: "TCN3DHead"
        num_classes: 11
        num_layers: 4
        sample_rate: 4
        sliding_window: 128
        seg_in_channels: 1280
        num_f_maps: 64
    loss:
        name: "StreamSegmentation"
        num_classes: 11
        sample_rate: 4
        backone_loss_weight: 1.0
        head_loss_weight: 1.0
        ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_keys: ["imgs", "flows", "labels", "masks"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        name: "RGBFlowFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        flows_path: "./data/gtea/flow"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RGBFlowFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/Videos"
        flows_path: "./data/gtea/flow"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        name: "RGBFlowFramePipeline"
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            rgb:
                - Resize:
                    size: 256
                - RandomCrop:
                    size: 224
                - RandomHorizontalFlip:
                - ToTensor:
                - Normalize:
                    mean: [0.551, 0.424, 0.179]
                    std: [0.133, 0.141, 0.124]
            flow:
                - Resize:
                    size: 256
                - RandomCrop:
                    size: 224
                - RandomHorizontalFlip:
                - ToTensor:
                - Normalize:
                    mean: [0.551, 0.424, 0.179]
                    std: [0.133, 0.141, 0.124]

    test:
        name: "RGBFlowFramePipeline"
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            rgb:
                - Resize:
                    size: 256
                - CenterCrop:
                    size: 224
                - ToTensor:
                - Normalize:
                    mean: [0.551, 0.424, 0.179]
                    std: [0.133, 0.141, 0.124]
            flow:
                - Resize:
                    size: 256
                - CenterCrop:
                    size: 224
                - ToTensor:
                - Normalize:
                    mean: [0.551, 0.424, 0.179]
                    std: [0.133, 0.141, 0.124]

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.0005 # 2 gpus * 2 batch size = 4
    step_size: [20, 40]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"
    file_output: True


model_name: "MulMod_3D_Memory_gtea_split1"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
