MODEL:
    architecture: "FeatureSegmentation"
    backbone:
    neck:
    head:
        name: "MultiStageModel"
        num_stages: 4
        num_layers: 4
        num_f_maps: 64
        dim: 2048
        num_classes: 11
    loss:
        name: "MSTCNLoss"
        num_classes: 11
        sample_rate: 4
        smooth_weight: 0.15
        ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_idx: 3

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/features"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/features"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        name: "FeaturePipline"
        decode:
            backend: "numpy"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            - ToTensor:

    test:
        name: "FeaturePipline"
        decode:
            backend: "numpy"
        sample:
            seg_len: 1
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            - ToTensor:

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.0005 # 2 gpus * 2 batch size = 4
    step_size: [20, 40]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"
    file_output: True


model_name: "Sliding_MSTCN_gtea_split1"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
