MODEL:
    architecture: "StreamSegmentation2D"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/tsm_mobilenetv2_dense_320p_1x1x8_100e_kinetics400_rgb_20210202-61135809.pth"
        clip_seg_num: 32
        shift_div: 8
        out_indices: (7, )
    neck:
        name: "AvgPoolNeck"
        num_classes: 21
        in_channels: 1280
        clip_seg_num: 32
        drop_ratio: 0.5
        need_pool: True
    head:
        name: "MultiStageModel"
        num_stages: 1
        num_layers: 4
        num_f_maps: 64
        dim: 1280
        num_classes: 21
        sample_rate: 4
    loss:
        name: "StreamSegmentationLoss"
        num_classes: 21
        sample_rate: 4
        backone_loss_weight: 1.0
        head_loss_weight: 1.0
        ignore_index: -100

POSTPRECESSING:
    name: "ScorePostProcessing"
    num_classes: 21
    clip_seg_num: 32
    sliding_window: 128
    sample_rate: 4
    ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks", "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 4
    num_workers: 2
    train:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/thumos14/val_list.txt" #Mandatory, train data index file path
        videos_path: "./data/thumos14/Videos"
        gt_path: "./data/thumos14/groundTruth"
        actions_map_file_path: "./data/thumos14/mapping.txt"
        dataset_type: "thumos14"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RawFrameSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/thumos14/test_list.txt" #Mandatory, train data index file path
        videos_path: "./data/thumos14/Videos"
        gt_path: "./data/thumos14/groundTruth"
        actions_map_file_path: "./data/thumos14/mapping.txt"
        dataset_type: "thumos14"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train:
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            is_train: True
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: [256, 320]
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.385, 0.383, 0.353]
                std: [0.258, 0.254, 0.248]

    test:
        name: "RawFramePipeline"
        decode:
            backend: "decord"
        sample:
            is_train: False
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            - Resize:
                size: [256, 320]
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.385, 0.383, 0.353]
                std: [0.258, 0.254, 0.248]

OPTIMIZER:
    name: "TSMAdamOptimizer"
    learning_rate: 0.001
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/thumos14/mapping.txt"
    file_output: True


model_name: "MobileNetV2TSM_MSTCN_thumos14"
log_interval: 5 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
