MODEL:
    architecture: "FeatureSegmentation"
    backbone:
    neck:
    head:
        name: "ASFormer"
        num_decoders: 0
        num_layers: 4
        r1: 2
        r2: 2
        num_f_maps: 64
        input_dim: 2048
        num_classes: 11
        sample_rate: 1
        channel_masking_rate: 0.5
    loss:
        name: "SegmentationLoss"
        num_classes: 11
        sample_rate: 1
        smooth_weight: 0.15
        ignore_index: -100

COLLATE:
    name: "BatchCompose"
    to_tensor_keys: ["faeture", "labels", "masks", "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/features"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 128
        sample_rate: 1
    test:
        name: "FeatureSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/features"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 128
        sample_rate: 1

POSTPRECESSING:
    name: "ScorePostProcessing"
    num_classes: 11
    clip_seg_num: 128
    sliding_window: 128
    sample_rate: 1
    ignore_index: -100

PIPELINE: #PIPELINE field
    train: 
        name: "BasePipline"
        decode:
            name: "FeatureDecoder"
            backend: "numpy"
        sample:
            name: "FeatureStreamSampler"
            is_train: True
            sample_rate: 1
            clip_seg_num: 128
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            name: "FeatureStreamTransform"
            transform_list:
                - ToTensor:

    test:
        name: "BasePipline"
        decode:
            name: "FeatureDecoder"
            backend: "numpy"
        sample:
            name: "FeatureStreamSampler"
            is_train: False
            sample_rate: 1
            clip_seg_num: 128
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            name: "FeatureStreamTransform"
            transform_list:
                - ToTensor:

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    name: "TASegmentationMetric"
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"
    file_output: True
    score_output: True


model_name: "Sliding_ASFormer_gtea_split1"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
