MODEL:
    architecture: "FeatureSegmentation"
    backbone:
    neck:
    head:
        name: "MultiStageModel"
        sample_rate: 1
        num_stages: 4
        num_layers: 10
        num_f_maps: 64
        dim: 2048
        num_classes: 11
    loss:
        name: "SegmentationLoss"
        num_classes: 11
        sample_rate: 1
        smooth_weight: 0.15
        ignore_index: -100

POSTPRECESSING:
    name: "StreamScorePostProcessing"
    num_classes: 11
    clip_seg_num: 32
    sliding_window: 32
    sample_rate: 1
    ignore_index: -100

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks" , "precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 2
    train:
        name: "FeatureStreamSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/features"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: True
        sliding_window: 32
        clip_seg_num: 32
        sample_rate: 1
    test:
        name: "FeatureStreamSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/gtea/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/gtea/features"
        gt_path: "./data/gtea/groundTruth"
        actions_map_file_path: "./data/gtea/mapping.txt"
        dataset_type: "gtea"
        train_mode: False
        sliding_window: 32
        clip_seg_num: 32
        sample_rate: 1

PIPELINE: #PIPELINE field
    train: 
        name: "BasePipline"
        decode:
            name: "FeatureDecoder"
            backend: "numpy"
        sample:
            name: "FeatureStreamSampler"
            is_train: True
            sample_rate: 1
            clip_seg_num: 32
            sliding_window: 32
            sample_mode: "uniform"
        transform:
            name: "FeatureStreamTransform"
            transform_list:
                - ToTensor:

    test:
        name: "BasePipline"
        decode:
            name: "FeatureDecoder"
            backend: "numpy"
        sample:
            name: "FeatureStreamSampler"
            is_train: False
            sample_rate: 1
            clip_seg_num: 32
            sliding_window: 32
            sample_mode: "uniform"
        transform:
            name: "FeatureStreamTransform"
            transform_list:
                - ToTensor:

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    name: "TASegmentationMetric"
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"
    file_output: True
    score_output: True


model_name: "Sliding_MSTCN_gtea_split1"
log_interval: 4 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
