MODEL:
    backbone:
        name: "ResNetTSM"
        pretrained: True
        depth: 50
        clip_seg_num: 30
        shift_div: 30
    neck:
        num_classes: 19
        num_layers: 4
        out_channel: 64
        in_channel: 2048
        clip_seg_num: 30
        drop_ratio: 0.5
        sample_rate: 20
    head:
        num_classes: 19
        num_layers: 4
        sliding_window: 600
        seg_in_channels: 2048
        sample_rate: 20
        num_f_maps: 64
    loss:
        num_classes: 19
        sample_rate: 20
        seg_weight: 1.0
        cls_weight: 1.0
        ignore_index: -100

COLLATE:
    to_tensor_idx: 3

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 4
    train:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/50salads/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/50salads/Videos"
        gt_path: "./data/50salads/groundTruth"
        actions_map_file_path: "./data/50salads/mapping.txt"
        dataset_type: "50salads"
        train_mode: True
        sliding_window: 600
        clip_seg_num: 30
        sample_rate: 20
    test:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/50salads/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/50salads/Videos"
        gt_path: "./data/50salads/groundTruth"
        actions_map_file_path: "./data/50salads/mapping.txt"
        dataset_type: "50salads"
        train_mode: False
        sliding_window: 600
        clip_seg_num: 30
        sample_rate: 20

PIPELINE: #PIPELINE field
    train: 
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 20
            clip_seg_num: 30
            sliding_window: 600
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: 256
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.513, 0.511, 0.479]
                std: [0.236, 0.233, 0.237]

    test:
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 20
            clip_seg_num: 30
            sliding_window: 600
            sample_mode: "uniform"
        transform:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.513, 0.511, 0.479]
                std: [0.236, 0.233, 0.237]

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.0005
    step_size: [50]
    gamma: 0.5

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/50salads/mapping.txt"
    file_output: True


model_name: "ETESVS_50salads_split1"
log_interval: 3 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10
