MODEL:
    architecture: "ETESVS"
    backbone:
        name: "MobileNetV2TSM"
        pretrained: "./data/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth"
        clip_seg_num: 32
        shift_div: 30
        out_indices: (6, 7, )
    neck:
        name: "ETESVSNeck"
        num_classes: 19
        num_layers: 1
        cls_in_channel: 1280
        cls_hidden_channel: 1280
        seg_in_channel: 320
        seg_hidden_channel: 320
        clip_seg_num: 32
        drop_ratio: 0.5
        bidirectional: False
    head:
        name: "ETESVSHead"
        num_classes: 19
        num_layers: 4
        sample_rate: 20
        sliding_window: 640
        seg_in_channels: 320
        num_f_maps: 64
    loss:
        name: "ETESVSLoss"
        num_classes: 19
        sample_rate: 20
        backone_loss_weight: 1.0
        neck_loss_weight: 1.0
        head_loss_weight: 1.0
        ignore_index: -100

COLLATE:
    to_tensor_idx: 3

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 2
    num_workers: 4
    train:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/50salads/splits/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/50salads/Videos"
        gt_path: "./data/50salads/groundTruth"
        actions_map_file_path: "./data/50salads/mapping.txt"
        dataset_type: "50salads"
        train_mode: True
        sliding_window: 640
        clip_seg_num: 32
        sample_rate: 20
    test:
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/50salads/splits/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/50salads/Videos"
        gt_path: "./data/50salads/groundTruth"
        actions_map_file_path: "./data/50salads/mapping.txt"
        dataset_type: "50salads"
        train_mode: False
        sliding_window: 640
        clip_seg_num: 32
        sample_rate: 20

PIPELINE: #PIPELINE field
    train: 
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 20
            clip_seg_num: 32
            sliding_window: 640
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            - Resize:
                size: [256, 320]
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - ToTensor:
            - Normalize:
                mean: [0.513, 0.511, 0.479]
                std: [0.236, 0.233, 0.237]

    test:
        decode:
            backend: "decord"
        sample:
            seg_len: 1
            sample_rate: 20
            clip_seg_num: 32
            sliding_window: 640
            sample_mode: "uniform"
        transform:
            - Resize:
                size: [256, 320]
            - CenterCrop:
                size: 224
            - ToTensor:
            - Normalize:
                mean: [0.513, 0.511, 0.479]
                std: [0.236, 0.233, 0.237]

OPTIMIZER: #OPTIMIZER field
    learning_rate: 0.0005
    step_size: [50]
    gamma: 0.5

METRIC:
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/50salads/mapping.txt"
    file_output: True


model_name: "ETESVS_MobileNetV2_50salads_split1"
log_interval: 3 #Optional, the interal of logger, default:10
epochs: 70 #Mandatory, total epoch
save_interval: 10
