MODEL:
    architecture: "Transeger"
    image_backbone:
        architecture: "Recognition2D"
        backbone:
            name: "MobileNetV2TSM"
            pretrained: "./data/tsm_mobilenetv2_dense_320p_1x1x8_100e_kinetics400_rgb_20210202-61135809.pth"
            clip_seg_num: 32
            shift_div: 8
            out_indices: (7, )
        neck:
            name: "AvgPoolNeck"
            num_classes: 178
            in_channels: 1280
            clip_seg_num: 32
            drop_ratio: 0.5
            need_pool: True
        head:
            name: "IdentityEmbeddingHead"
            in_channels: 1280
            out_channels: 64
            sample_rate: 4
    text_backbone:
        architecture: "Encoder2Decoder"
        encoder:
            name: "LearnerPromptTextEncoder"
            actions_map_file_path: "./data/breakfast/mapping_fine.txt"
            embedding_dim: 512
            sample_rate: 4
            max_len: 50
            clip_seg_num: 32
            encoder_layers_num: 3
            encoder_heads_num: 8
            text_embed_dim: 64
        decoder:
        head:
    joint:
        name: "TransegerMemoryTCNJointNet"
        num_classes: 178
        in_channels: 64
        hidden_channels: 128
        num_layers: 4
        sample_rate: 4
    loss:
        name: "SegmentationLoss"
        num_classes: 178
        sample_rate: 4
        smooth_weight: 0.5
        ignore_index: -100
        class_weight: [0.0155,0.0120,0.0190,0.0079,0.0143,0.0317,0.0747,0.0188,0.0156,0.0030,0.0569,0.0256,0.0028,0.0238,0.0153,0.0143,0.0357,0.0243,0.0027,
            0.0086,0.0248,0.1825,0.0077,0.1785,0.0400,0.0193,0.0192,0.0133,0.0258,0.1029,0.1474,0.0123,0.0162,0.0011,0.0491,0.0342,0.0111,0.0686,0.0185,
            0.0031,0.0632,0.0046,0.0291,0.0100,0.0196,0.0372,0.1403,0.0056,0.0044,0.0104,0.0062,0.0372,0.0278,0.0167,0.0175,0.0105,0.0480,0.0801,0.0094,
            0.0090,0.0209,0.0155,0.0042,0.0130,0.0071,0.0135,0.0204,0.0629,0.0025,0.1764,0.0172,0.0118,0.0884,0.0367,0.1943,0.1349,0.0036,0.0097,0.0046,
            0.0270,0.0088,0.0291,0.0098,0.0706,0.0072,0.0156,0.0504,0.0385,0.0066,0.0025,0.0076,0.0482,0.0075,0.0082,0.0442,0.0338,0.0361,0.0720,0.0148,
            0.4890,0.0124,0.1260,0.0240,0.0030,0.0327,0.0245,0.0063,0.0241,0.0260,0.0174,0.0032,0.0142,0.0060,0.0526,0.0227,0.0152,0.2772,0.0375,0.0208,
            0.0136,0.0095,0.0358,0.0073,0.2259,0.0135,0.0170,0.0104,0.0116,0.0132,0.1438,0.0173,0.1899,0.0102,0.0592,0.0044,0.0869,0.0083,0.0681,0.0569,
            0.0553,0.0109,0.4144,0.0205,0.0490,0.0098,0.0219,0.0359,0.0431,0.0769,0.0121,0.0725,0.0490,0.0050,0.0059,0.0102,0.0227,0.0037,0.0081,0.0131,
            0.0340,0.0540,0.0329,0.0099,0.0118,0.0054,0.0150,0.0095,0.0287,0.1708,0.0350,0.1928,0.0064,0.0066,0.0218,0.0074,0.0324,0.0390,0.1072]

POSTPRECESSING:
    name: "StreamScorePostProcessing"
    num_classes: 178
    clip_seg_num: 32
    sliding_window: 128
    sample_rate: 4
    ignore_index: -100

COLLATE:
    name: "StreamBatchCompose"
    to_tensor_keys: ["imgs", "labels", "masks" ,"precise_sliding_num"]

DATASET: #DATASET field
    temporal_clip_batch_size: 3
    video_batch_size: 4
    num_workers: 4
    train:
        name: "RawFrameStreamSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits_fine/train.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth_fine"
        actions_map_file_path: "./data/breakfast/mapping_fine.txt"
        dataset_type: "breakfast"
        train_mode: True
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4
    test:
        name: "RawFrameStreamSegmentationDataset"
        data_prefix: "./" #Mandatory, train data root path
        file_path: "./data/breakfast/splits_fine/test.split1.bundle" #Mandatory, train data index file path
        videos_path: "./data/breakfast/Videos"
        gt_path: "./data/breakfast/groundTruth_fine"
        actions_map_file_path: "./data/breakfast/mapping_fine.txt"
        dataset_type: "breakfast"
        train_mode: False
        sliding_window: 128
        clip_seg_num: 32
        sample_rate: 4

PIPELINE: #PIPELINE field
    train: 
        name: "BasePipline"
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "VideoStreamSampler"
            is_train: True
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform: #Mandotary, image transform operator.
            name: "VideoStreamTransform"
            transform_list:
                - Resize:
                    size: [256, 320]
                - RandomCrop:
                    size: 256
                - RandomHorizontalFlip:
                - ToTensor:
                - Normalize:
                    mean: [0.425, 0.390, 0.337]
                    std: [0.262, 0.260, 0.246]

    test:
        name: "BasePipline"
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "VideoStreamSampler"
            is_train: False
            sample_rate: 4
            clip_seg_num: 32
            sliding_window: 128
            sample_mode: "uniform"
        transform:
            name: "VideoStreamTransform"
            transform_list:
                - Resize:
                    size: [256, 320]
                - CenterCrop:
                    size: 256
                - ToTensor:
                - Normalize:
                    mean: [0.425, 0.390, 0.337]
                    std: [0.262, 0.260, 0.246]

OPTIMIZER:
    name: "AdamOptimizer"
    learning_rate: 0.0005
    weight_decay: 1e-4
    betas: (0.9, 0.999)

LRSCHEDULER:
    name: "MultiStepLR"
    step_size: [50]
    gamma: 0.1

METRIC:
    name: "TASegmentationMetric"
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/breakfast/mapping_fine.txt"
    file_output: True


model_name: "Transeger_breakfast_split1"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 35 #Mandatory, total epoch
save_interval: 35
